---
title: Base R Plots
date: 2024-06-02
format: 
  html:
    fig-width: 8
    fig-height: 4
    code-fold: true
---

```{r}
# Generate some sample data
set.seed(123)
x <- rnorm(100)
y <- rnorm(100)
summary(x)
summary(y)
```

# Basic scatter Plot
```{r}
plot(x, y, main = "Scatter Plot", xlab = "X-axis", ylab = "Y-axis")
```

# Histogram
```{r}
hist(x, main = "Histogram", xlab = "X-axis", breaks = 10, col = "blue")
```
# Boxplot
```{r}
boxplot(x, main = "Boxplot", ylab = "Values")
```
# Table function
```{r}
table(round(x))
```
# Barplot
```{r}
barplot(table(round(x)), main = "Bar Plot", xlab = "Values", col = "green")
```
# Pie chart
```{r}
pie(table(round(x)), main = "Pie Chart")
```
# Density plot
```{r}
density(x)
```
```{r}
plot(density(x), main = "Density Plot", xlab = "Values")
```
# Pairs plot
```{r}
pairs(~x + y, main = "Pairs Plot")
```
# Image plot
```{r}
matrix_data <- matrix(rnorm(100), nrow = 10)
```
```{r}
image(matrix_data, main = "Image Plot")
```
# Contour plot
```{r}
contour(volcano, main = "Contour Plot")
```
# 3D perspective plot
```{r}
persp(volcano, main = "3D Perspective Plot")
```
# QQ plot
```{r}
qqnorm(x)
qqline(x, col = "red")
```